contact_links:
  - name: Asking a Question/Starting a Discussion.
    url: https://github.com/Amirhan-Taipovjan-Greatest-I/.github/discussions
    about: Want to Discuss? It should be there, not in Issues.
  - name: Wanting to contact Me.
    url: https://amirhan-taipovjan-greatest-i.github.io/main%23en
    about: Want to contact Me? There's My Card Site with all Socials of Mine.
